services:

  event:
    container_name: event
    image: cloud-transcription-app-event:local-latest
    build:
      context: ./event
      target: dev
    env_file:
      - ./event/.env
    volumes:
    - ./event/src:/src

  terraform:
    container_name: terraform
    image: cloud-transcription-app-terraform:local-latest
    build:
      context: ./terraform
    env_file:
    - ./terraform/.env
    volumes:
    - ./terraform/infra:/home/terraform/infra
