services:

  event:
    container_name: event
    image: cloud-transcription-app-event:local-latest
    build:
      context: ./event
      target: local
    env_file:
      - ./event/.env
    volumes:
    - ./event/src:/src

  infra:
    container_name: infra
    image: cloud-transcription-app-infra:local-latest
    build:
      context: ./infra
    env_file:
    - ./infra/.env
    volumes:
    - ./infra/src:/home/terraform/infra