name: Build Event Function
on:
  push:
    branches:
      - main
    # paths:
    #   - 'event/**'
    #   - '.github/workflows/build-event-function.yml'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        group: [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.MY_GITHUB_ACCESS_TOKEN }}
          fetch-depth: 0
          sparse-checkout: 'event/'
        
      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.3
        with:
          version: v0.61.0
              
      - name: Configure AWS Credentials for Japan region audience
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          audience: sts.amazonaws.com
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_OIDC_ARN }}

      - name: Login To ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Image Pipeline
        run: |
          for target in $(ls -1 ./event/src | grep -n ^ | grep ${{ matrix.group }}: | awk -F : '{print $2}'); do
            git diff --name-only HEAD^..HEAD | grep -e ^event/Dockerfile -e ^event/src/${target} || continue
            docker build -t ${{ secrets.IMAGE_REGISTRY_URI }}:${target}-${{ github.sha }} --target prod --build-arg BUILD_TARGET=${target} --provenance=false ./event
            trivy image --severity HIGH,CRITICAL --exit-code 1 ${{ secrets.IMAGE_REGISTRY_URI }}:${target}-${{ github.sha }}
            docker push ${{ secrets.IMAGE_REGISTRY_URI }}:${target}-${{ github.sha }}
          done
  
  call-deploy:   
    uses: ./.github/workflows/deploy.yml
    needs: build
    secrets:
      MY_GITHUB_ACCESS_TOKEN: ${{ secrets.MY_GITHUB_ACCESS_TOKEN }}
      AWS_ROLE_TO_ASSUME_OIDC_ARN: ${{ secrets.AWS_ROLE_TO_ASSUME_OIDC_ARN }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      TFSTATE_S3_BUCKET_ARN: ${{ secrets.TFSTATE_S3_BUCKET_ARN }}
      NOTIFICATION_EMAIL_ADDRESS: ${{ secrets.NOTIFICATION_EMAIL_ADDRESS }}
      MODEL_ID: ${{ secrets.MODEL_ID }}
